### ISSUE TITLE
Cross platform support?

### ISSUE THREAD

**Issue by ghost** [kris701/ArduLED#6]
Forgive me if this is a stupid question,

is it possible to run this on Linux or Mac? I only see the .exe

**Comment by kris701** [comment]
I am so sorry, no this program only works on windows. This is because all the visual elements are made in WinForms. However it may be possable to port it over to a more Xamarin style forms, that i am not sure about tho. As it looks like for now i will not add Linux ro Mac support, that would be a larger project for the future.
But thank you for asking.
